# .github/workflows/rubocop.yml

name: RuboCop

on:
  pull_request:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 3.0.0

      - name: Install Bundler
        run: gem install bundler
      
      - name: Install dependencies
      run: |
        bundle config set path vendor/bundle
        bundle install

    - name: Database configuration
      run: rails db:migrate

    - name: Run RuboCop
      run: bundle exec rubocop