# .github/workflows/rubocop.yml

name: RuboCop

on:
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Database configuration
      run: rails db:migrate

    - name: Run RuboCop
      run: bundle exec rubocop